---
name: Build Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          npm install
          echo "TypeScript version:"
          npx tsc --version
          echo "Node version:"
          node --version
          echo "Contents of node_modules/@types/node:"
          ls -la node_modules/@types/node/
          echo "Contents of node_modules/typescript/lib:"
          ls -la node_modules/typescript/lib/
      
      - name: Show TypeScript Config
        run: |
          echo "tsconfig.json contents:"
          cat tsconfig.json
          echo "TypeScript compiler options:"
          npx tsc --showConfig
      
      - name: Compile TypeScript
        run: |
          echo "Running TypeScript compiler in verbose mode:"
          npx tsc -p ./ --listFiles --traceResolution
      
      - name: Create Release Package
        run: |
          mkdir -p release
          cp -r out media package.json HOWTO.md release/
          cd release
          zip -r ../task-runner-files.zip *
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-runner-files
          path: task-runner-files.zip