---
name: Build Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'npm'
      
      - name: Clean Install Dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npm install -D @types/node@16
          npm install -D typescript@4.9.5
      
      - name: Verify TypeScript Installation
        run: |
          tsc --version
          ls -la node_modules/typescript/lib/
          ls -la node_modules/@types/node/
      
      - name: Compile TypeScript
        run: npm run compile
      
      - name: Create Release Package
        run: |
          mkdir -p release
          cp -r out media package.json HOWTO.md release/
          cd release
          zip -r ../task-runner-files.zip *
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-runner-files
          path: task-runner-files.zip