name: Build Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      
      - name: Install dependencies
        run: npm install
      
      - name: Compile TypeScript
        run: npm run compile
      
      - name: Package Extension
        run: npx vsce package
      
      - name: Create Release Package
        run: |
          mkdir -p release
          cp -r out node_modules media package.json HOWTO.md release/
          cd release && zip -r ../task-runner-files.zip *
      
      - name: Upload VSIX
        uses: actions/upload-artifact@v3
        with:
          name: task-runner-dashboard-vsix
          path: "*.vsix"
          retention-days: 1
          if-no-files-found: error
      
      - name: Upload Release Files
        uses: actions/upload-artifact@v3
        with:
          name: task-runner-files
          path: task-runner-files.zip
          retention-days: 1
          if-no-files-found: error